#
# Broadcom Linux Router Makefile
# 
# Copyright 2004, Broadcom Corporation
# All Rights Reserved.
# 
# THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
# KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
# SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
#
# $Id$
#

include .config

RELEASE=1.9.2.7-d


MODEL=WL500gp
# WL500gx, WL550gE, WL500gp, WL500gpv2, WL500W

#
# asus trx trailer
#

KERNEL_VER=1.9
FS_VER=2.7
HWL1=0.02
HWH1=2.99

#
# Paths
#

# Source bases
export PLATFORM LINUXDIR LIBDIR USRLIBDIR
export TOP := $(shell pwd)
export SRCBASE := $(shell (cd $(TOP)/.. && pwd -P))

#
# Cross-compile environment variables
#

# Build platform
export BUILD := $(shell (gcc -dumpmachine))
export HOSTCC := gcc
export HOSTCXX := g++

# uClibc wrapper
ifeq ($(CONFIG_UCLIBC),y)
export PLATFORM := $(PLATFORM)-uclibc
endif

ifeq ($(PLATFORM),mipsel)
export CROSS_COMPILE := mipsel-linux-
export CONFIGURE := ./configure --host=mipsel-linux --build=$(BUILD)
export TOOLCHAIN := $(shell cd $(dir $(shell which $(CROSS_COMPILE)gcc))/../mipsel-linux && pwd -P)
endif

ifeq ($(PLATFORM),mipsel-uclibc)
export CROSS_COMPILE := mipsel-uclibc-
export CONFIGURE := ./configure --host=mipsel-linux --build=$(BUILD)
export TOOLCHAIN := $(shell cd $(dir $(shell which $(CROSS_COMPILE)gcc))/.. && pwd -P)
endif

ifeq ($(CONFIG_BCMWPA2),y)
EXTRACFLAGS += -DBCMWPA2 
endif

ifeq ($(CONFIG_IPV6),y)
export CONFIG_IPV6 := y
else
CONFIG_IPV6 :=
endif

export CC := $(CROSS_COMPILE)gcc
export AR := $(CROSS_COMPILE)ar
export AS := $(CROSS_COMPILE)as
export LD := $(CROSS_COMPILE)ld
export NM := $(CROSS_COMPILE)nm
export RANLIB := $(CROSS_COMPILE)ranlib
export STRIP := $(CROSS_COMPILE)strip
export SIZE := $(CROSS_COMPILE)size

#
# Install and target directories
#

export PLATFORMDIR := $(TOP)/$(PLATFORM)
export INSTALLDIR := $(PLATFORMDIR)/install
export TARGETDIR := $(PLATFORMDIR)/target

# Determine kernel version
LINUX_KERNEL=$(subst ",,$(word 3, $(shell grep "UTS_RELEASE" $(LINUXDIR)/include/linux/version.h)))
export MODULESDIR := $(TARGETDIR)/lib/modules/$(LINUX_KERNEL)
SRCMODULESDIR := $(PLATFORMDIR)/modules/lib/modules/*/kernel

# always build libbcmcrypto, required by nas
obj-y += libbcmcrypto 

ifeq ($(CONFIG_LIBUSB),y)
obj-$(CONFIG_LIBUSB) += libusb10
endif

#
# Configuration
#

obj-$(CONFIG_HTTPD) += httpd
obj-$(CONFIG_RC) += rc
obj-$(CONFIG_LIBBCM) += libbcm
obj-$(CONFIG_SHARED) += shared
obj-$(CONFIG_WWW) += www
obj-$(CONFIG_GLIBC) += lib
obj-$(CONFIG_UCLIBC) += lib
obj-$(CONFIG_WLCONF) += wlconf
obj-$(CONFIG_BRIDGE) += bridge
obj-$(CONFIG_BUSYBOX) += busybox
obj-$(CONFIG_DNSMASQ) += dnsmasq
obj-$(CONFIG_IPTABLES) += iptables
obj-$(CONFIG_LIBIPT) += iptables
obj-$(CONFIG_NETCONF) += netconf
obj-$(CONFIG_NVRAM) += nvram
obj-$(CONFIG_PPP) += ppp
obj-$(CONFIG_UDHCPD) += udhcpd
obj-$(CONFIG_UPNP) += upnp
obj-$(CONFIG_MINIUPNPD) += miniupnpd
obj-$(CONFIG_UTILS) += utils
obj-$(CONFIG_ETC) += etc

# Added by Joey for ASUS application
obj-$(CONFIG_PPTP) += pptp
obj-$(CONFIG_ACCEL_PPTP) += accel-pptp
obj-$(CONFIG_PPPOERELAY) += rp-pppoe
obj-$(CONFIG_EZIPUPDATE) += ez-ipupdate
obj-$(CONFIG_JPEG6B) += jpeg-6b
obj-$(CONFIG_RCAMD) += rcamdmips
obj-$(CONFIG_LPRNG) += LPRng
obj-$(CONFIG_OTHERS) += others
obj-$(CONFIG_BPALOGIN) += bpalogin
obj-$(CONFIG_WAVESERVER) += waveserver
obj-$(CONFIG_EMF) += emf
obj-$(CONFIG_EMF) += igs

# custom firmware
obj-$(CONFIG_SSHD) += dropbear
obj-$(CONFIG_JETDIRECT) += p910nd
obj-$(CONFIG_SAMBA) += samba
obj-$(CONFIG_NFSD) += nfs-utils
obj-$(CONFIG_NFSD) += portmap
obj-$(CONFIG_IPROUTE2) += iproute2
obj-$(CONFIG_LOADER) += loader
obj-$(CONFIG_IPV6) += radvd
obj-$(CONFIG_SNMP) += ucd-snmp
obj-$(CONFIG_L2TP) += rp-l2tp
obj-$(CONFIG_XL2TPD) += xl2tpd
obj-$(CONFIG_IGMPPROXY) += igmpproxy
obj-$(CONFIG_VSFTPD) += vsftpd
obj-$(CONFIG_INADYN) += inadyn
obj-$(CONFIG_SCSIIDLE) += scsi-idle
obj-$(CONFIG_USBMODESWITCH) += usb_modeswitch
obj-$(CONFIG_MADWIMAX) += madwimax
obj-$(CONFIG_MODEM) += cdma
obj-$(CONFIG_LLTD) += lltd
obj-y += udpxy

obj-y += kernel

# Netfilter modules NOT to include in main FW
netfilter_external_modules := ipt_layer7.o ip_set.o \
 ip_set_ipmap.o ip_set_iptree.o ip_set_iptreemap.o ip_set_macipmap.o \
 ip_set_nethash.o ip_set_iphash.o \
 ip_set_portmap.o ip_set_ipporthash.o ip_set_ipportiphash.o \
 ip_set_ipportnethash.o ip_set_setlist.o ipt_SET.o ipt_set.o \
 ip_conntrack_rtsp.o ip_nat_rtsp.o ip_conntrack_sip.o ip_nat_sip.o \
 ip6_conntrack.o ip6_conntrack_ftp.o

obj-clean := $(foreach obj,$(obj-y) $(obj-n),$(obj)-clean)
obj-install := $(foreach obj,$(obj-y),$(obj)-install)

# defaults
export LANGUAGE := "EN"
GLOBAL_OPTIONS := -DUSB_SUPPORT -DQOS -DWPA2_WMM

LZMADIR=$(SRCBASE)/lzma/CPP/7zip/Compress

SVNREVISION:=$(shell cat $(TOP)/.svnrev 2>/dev/null)
ifneq (0,$(words $(SVNREVISION)))
  RELEASE:=$(RELEASE)-r$(firstword $(SVNREVISION))
endif

# $1 - config name, $2 - params list to change, $3 - new param value (y/n/m)
define SwitchConfParam
	@( \
	SW_SEDCMD=""; \
	for SW_PARAM in $(2); do \
	 ORIG_STR=`grep -w "$${SW_PARAM}" $(1) 2>/dev/null`; \
	 if [ "$(3)" = "n" ]; then \
	    TEST_PATTERN="# $${SW_PARAM} is not set"; \
	 else \
	    TEST_PATTERN="$${SW_PARAM}=$(3)"; \
	 fi; \
	 IS_SAME_VALUE=`echo $${ORIG_STR} | grep "$${TEST_PATTERN}" 2>/dev/null`; \
	 if [ "$${IS_SAME_VALUE}" = "" ]; then \
	    SW_SEDCMD="$${SW_SEDCMD};s/$${ORIG_STR}/$${TEST_PATTERN}/"; \
	 fi; \
	done; \
	if [ "$${SW_SEDCMD}" != "" ]; then \
	    sed "$${SW_SEDCMD}" $(1) >$(1).sed; \
	    mv $(1).sed $(1); \
	fi; \
	)
endef

FlashMaxSize = \
    $(if $(filter $(1),WL520gc),1703936, \
    $(if $(filter $(1),WL500gx WL550gE WL320gE WL320gP WL520gu WL330gE RT-N10 RT-N12),3801880, \
    $(if $(filter $(1),WL500gp WL500W WL500gpv2 WL700g),7995392, \
    $(if $(filter $(1),RT-N16),16384000,0)))) \

#
# Basic rules
#

all: $(obj-y) 

clean: $(obj-clean) config-clean lzma-clean
	rm -rf $(TARGETDIR)
	rm -f $(PLATFORMDIR)/vmlinuz $(PLATFORMDIR)/target.cramfs
	$(MAKE) -C $(LINUXDIR) clean

distclean mrproper: clean
	rm -f .config $(LINUXDIR)/.config

lzma-lib:
	$(MAKE) -C $(LZMADIR)/LZMA_Lib/ CC=$(HOSTCC) CXX=$(HOSTCXX)

lzma-lib-clean:
	$(MAKE) -C $(LZMADIR)/LZMA_Lib/ clean

lzma:
	$(MAKE) -C $(LZMADIR)/LZMA_Alone/ -f makefile.gcc

lzma-clean: lzma-lib-clean
	$(MAKE) -C $(LZMADIR)/LZMA_Alone/ -f makefile.gcc clean

loader:
	$(MAKE) -C $@ LZMAPATH=$(SRCBASE)/lzma/C/Compress/Lzma EXTRACFLAGS="$(EXTRACFLAGS)"

mksquashfs-lzma: lzma-lib $(LINUXDIR)/scripts/squashfs/mksquashfs-lzma
	$(MAKE) -C $(LINUXDIR)/scripts/squashfs mksquashfs-lzma \
		LZMAPATH=$(LZMADIR)/LZMA_Lib CC=$(HOSTCC) CXX=$(HOSTCXX)


kernel-modules: $(LINUXDIR)/.config
	( . $(LINUXDIR)/.config ; \
	if [ "$${CONFIG_MODULES}" = "y" ] ; then \
	    $(MAKE) -C $(LINUXDIR) modules CC=$(CROSS_COMPILE)gcc-3.4.6; \
	fi )

kernel-image: $(LINUXDIR)/.config
	( . $(LINUXDIR)/.config ; \
	if [ "$${CONFIG_EMBEDDED_RAMDISK}" = "" ] ; then \
	    $(MAKE) -C $(LINUXDIR) zImage CC=$(CROSS_COMPILE)gcc-3.4.6; \
	fi )

$(LINUXDIR)/fs/fuse/Makefile:
	cd $(LINUXDIR)/fs/fuse && \
	$(CONFIGURE) --enable-kernel-module --with-kernel=$(LINUXDIR) CC=$(CROSS_COMPILE)gcc-3.4.6

fuse-driver: $(LINUXDIR)/.config $(LINUXDIR)/fs/fuse/Makefile
	cd $(LINUXDIR)/fs/fuse && $(MAKE)

kernel: kernel-image kernel-modules fuse-driver
	@true

kernel-clean:
	$(MAKE) -C $(LINUXDIR) clean

kernel-install: lzma
ifeq ($(CONFIG_LOADER),y)
	cat $(LINUXDIR)/arch/mips/bcm947xx/compressed/piggy | \
		$(LZMADIR)/LZMA_Alone/lzma e -si -so -lc1 -lp2 -pb2 > $(PLATFORMDIR)/vmlinuz
else
	cp $(LINUXDIR)/arch/mips/bcm947xx/compressed/vmlinuz $(PLATFORMDIR)/
endif
	( . $(LINUXDIR)/.config ; \
	if [ "$${CONFIG_MODULES}" = "y" ] ; then \
	    $(MAKE) -C $(LINUXDIR) modules_install DEPMOD=/bin/true INSTALL_MOD_PATH=$(PLATFORMDIR)/modules ; \
	    cd $(LINUXDIR)/fs/fuse && $(MAKE) install DEPMOD=/bin/true INSTALL_MOD_PATH=$(PLATFORMDIR)/modules; \
	    $(TOP)/busybox/examples/depmod.pl -b $(PLATFORMDIR)/modules/lib/modules/* -F $(LINUXDIR)/System.map; \
	fi )
	rm -f $(PLATFORMDIR)/modules/lib/modules/*/build

NETFILTER_MODS_LIST:=$(filter-out $(patsubst %.o,\%/%.o,$(netfilter_external_modules)),$(shell ls -1 $(SRCMODULESDIR)/net/ipv4/netfilter/*.o 2>/dev/null))
ifeq ($(CONFIG_IPV6),y)
NETFILTER_MODS_LIST+=$(filter-out $(patsubst %.o,\%/%.o,$(netfilter_external_modules)),$(shell ls -1 $(SRCMODULESDIR)/net/ipv6/netfilter/*.o 2>/dev/null))
endif

modules_install-WL3%: modules_install
	install -t $(MODULESDIR) \
		$(NETFILTER_MODS_LIST)
#	rm -rf $(MODULESDIR)/parport
	@true

modules_install-WL500gx modules_install-WL500gp modules_install-WL500W: modules_install
	install -t $(MODULESDIR) \
		$(NETFILTER_MODS_LIST)
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/usb/host/usb-uhci.o \
		$(SRCMODULESDIR)/drivers/usb/host/ehci-hcd.o 

modules_install-WL700g: modules_install
	install -t $(MODULESDIR) \
		$(NETFILTER_MODS_LIST)
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/usb/host/usb-uhci.o \
		$(SRCMODULESDIR)/drivers/usb/host/ehci-hcd.o \
		$(SRCMODULESDIR)/drivers/char/gpiortc.o \
		$(SRCMODULESDIR)/drivers/ide/ide-core.o \
		$(SRCMODULESDIR)/drivers/ide/ide-disk.o \
		$(SRCMODULESDIR)/drivers/ide/ide-detect.o \
		$(SRCMODULESDIR)/drivers/ide/pci/aec62xx.o 

modules_install-WL550gE modules_install-WL520gu modules_install-WL500gpv2: modules_install
	install -t $(MODULESDIR) \
		$(NETFILTER_MODS_LIST)
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/usb/host/usb-ohci.o \
		$(SRCMODULESDIR)/drivers/usb/host/ehci-hcd.o 

modules_install-WL520gc: modules_install
	install -t $(MODULESDIR) \
		$(NETFILTER_MODS_LIST)

modules_install: .config
	install -d $(MODULESDIR)
	# network stuff
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/net/et/et.o \
		$(SRCMODULESDIR)/drivers/net/wl/wl.o
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/net/tun.o \
		$(SRCMODULESDIR)/drivers/net/imq.o
ifeq ($(CONFIG_EMF),y)
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/net/emf/emf.o \
		$(SRCMODULESDIR)/drivers/net/igs/igs.o
endif
	# NLS
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/fs/nls/nls_cp950.o
	# generic usb
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/usb/usbcore.o \
		$(SRCMODULESDIR)/drivers/usb/printer.o
	# usb storage
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/usb/storage/usb-storage.o \
		$(SRCMODULESDIR)/drivers/scsi/sd_mod.o \
		$(SRCMODULESDIR)/drivers/scsi/scsi_mod.o
	# usb serial
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/usb/serial/usbserial.o \
		$(SRCMODULESDIR)/drivers/usb/serial/pl2303.o \
		$(SRCMODULESDIR)/drivers/usb/serial/ftdi_sio.o \
		$(SRCMODULESDIR)/drivers/usb/serial/option.o \
		$(SRCMODULESDIR)/drivers/usb/acm.o 
	# usb webcams
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/media/video/videodev.o \
		$(SRCMODULESDIR)/drivers/usb/ov51x.o \
		$(SRCMODULESDIR)/drivers/usb/ov511_decomp.o \
		$(SRCMODULESDIR)/drivers/usb/ov518_decomp.o \
		$(SRCMODULESDIR)/drivers/usb/pwc.o \
		$(SRCMODULESDIR)/drivers/usb/pwcx.o
	# usb audio
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/drivers/usb/audio.o \
		$(SRCMODULESDIR)/drivers/sound/soundcore.o
ifeq ($(CONFIG_NFSD),y)
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/fs/lockd/*.o \
		$(SRCMODULESDIR)/fs/nfsd/*.o	\
		$(SRCMODULESDIR)/net/sunrpc/*.o
endif
ifeq ($(CONFIG_NFS),y)
	install -t $(MODULESDIR) \
		$(SRCMODULESDIR)/fs/nfs/*.o
endif

install: package-$(MODEL)
	@true

package-%: $(filter-out lib-install www-install,$(obj-install)) $(LINUXDIR)/.config mksquashfs-lzma
	$(MAKE) www-pages-$*
	# Install binaries into target directory
	rm -rf $(TARGETDIR) && install -d $(TARGETDIR)
	echo $(RELEASE) > $(TARGETDIR)/.version
	for dir in $(wildcard $(patsubst %,$(INSTALLDIR)/%,$(obj-y))) $(INSTALLDIR)/www ; do \
	    (cd $${dir} && tar cpf - .) | (cd $(TARGETDIR) && tar xpf -) \
	done
	# Optimize crypto library
	$(MAKE) -C libbcmcrypto optimize
	# Install (and possibly optimize) C library
	$(MAKE) lib-install
	# statically linked ASUS shit
ifeq ($(CONFIG_WAVESERVER),y)
	$(STRIP) others/waveserver -o $(TARGETDIR)/usr/sbin/waveserver
endif
	# Install binary Addons, if any
	@-( if [ -d $(SRCBASE)/router/Addon ]; then \
	    ( cp -dup $(SRCBASE)/router/Addon/* $(TARGETDIR)/usr/sbin/ ) \
	fi )
	# Install modules into filesystem
	$(MAKE) modules_install-$*
	# Prepare filesystem
	cd $(TARGETDIR) && $(TOP)/misc/rootprep.sh
	$(LINUXDIR)/scripts/squashfs/mksquashfs-lzma $(TARGETDIR) $(PLATFORMDIR)/target.cramfs -all-root -noappend -nopad
	rm -f $(PLATFORMDIR)/$*-$(RELEASE).trx
	$(MAKE) -C $(SRCBASE)/asustrx CC=$(HOSTCC)
ifeq ($(CONFIG_LOADER),y)
	$(SRCBASE)/asustrx/asustrx -p $* -v $(KERNEL_VER).$(FS_VER) -m $(call FlashMaxSize,$*) \
		-o $(PLATFORMDIR)/$*-$(RELEASE).trx \
		loader/loader.gz $(PLATFORMDIR)/vmlinuz $(PLATFORMDIR)/target.cramfs
else
	$(SRCBASE)/asustrx/asustrx -p $* -v $(KERNEL_VER).$(FS_VER) -m $(call FlashMaxSize,$*) \
		-o $(PLATFORMDIR)/$*-$(RELEASE).trx \
		$(PLATFORMDIR)/vmlinuz $(PLATFORMDIR)/target.cramfs
endif
	@echo
	@echo "Finished building $* firmware version $(KERNEL_VER).$(FS_VER) ($(RELEASE))"
	@echo


MANPAGES-y := busybox/docs/BusyBox.1 \
	    LPRng/man/lpd.8 bridge/doc/brctl.8 dnsmasq/man/dnsmasq.8 \
	    dropbear/dbclient.1 dropbear/dropbear.8 dropbear/dropbearkey.8 \
	    igmpproxy/doc/igmpproxy.8 igmpproxy/doc/igmpproxy.conf.5 \
	    iptables/iptables.8 iptables/iptables-restore.8 iptables/iptables-save.8 \
	    p910nd/p910nd.8 ppp/chat/chat.8 ppp/pppd/pppd.8 pptp/pptp.8 \
	    ucd-snmp/man/snmpd.1 ucd-snmp/man/snmpd.conf.5 \
	    vsftpd/vsftpd.8 vsftpd/vsftpd.conf.5

MANPAGES-$(CONFIG_SAMBA) += samba/docs/manpages/smb.conf.5 \
	    samba/docs/manpages/smbpasswd.8 samba/docs/manpages/nmbd.8 samba/docs/manpages/smbd.8
MANPAGES-$(CONFIG_IPV6) += iptables/ip6tables.8 iptables/ip6tables-restore.8 iptables/ip6tables-save.8
MANPAGES-$(CONFIG_INADYN) += inadyn/man/inadyn.conf.5 inadyn/man/inadyn.8
MANPAGES-$(CONFIG_NTFS3G) += ntfs-3g/src/ntfs-3g.8
MANPAGES-$(CONFIG_RIPD) += quagga/doc/ospfd.8 quagga/doc/ripd.8 quagga/doc/zebra.8

manpages-install:
	$(MAKE) -C LPRng/man
	@mkdir -p $(PLATFORMDIR)/manpages/man/man8 \
	    $(PLATFORMDIR)/manpages/man/man1 $(PLATFORMDIR)/manpages/man/man5
	install --mode=0644 -t $(PLATFORMDIR)/manpages/man/man8 \
	    $(filter %.8,$(MANPAGES-y))
	install --mode=0644 -t $(PLATFORMDIR)/manpages/man/man1 \
	    $(filter %.1,$(MANPAGES-y))
	install --mode=0644 -t $(PLATFORMDIR)/manpages/man/man5 \
	    $(filter %.5,$(MANPAGES-y))
ifeq ($(CONFIG_NFSD),y)
	for subdir in exportfs lockd mountd nfsd statd; do \
	$(MAKE) -C nfs-utils/utils/$${subdir} install-man DESTDIR=$(PLATFORMDIR)/ datarootdir=manpages ; \
	done
endif
ifeq ($(CONFIG_IPV6),y)
	$(MAKE) -C radvd install-man DESTDIR=$(PLATFORMDIR)/manpages
endif

modules: kernel-install
	tar -C $(PLATFORMDIR)/$@ -czf $(PLATFORMDIR)/$@-$(RELEASE).tgz .

manpages: manpages-install
	tar -C $(PLATFORMDIR)/$@ -czf $(PLATFORMDIR)/$@-$(RELEASE).tgz .

#
# Configuration rules
#

conf mconf:
	$(MAKE) -C config
	@./config/$@ ./config/Config
	# Also configure kernel
	$(MAKE) k$@

oldconf: .config
	$(MAKE) -C config
	@./config/conf -o ./config/Config
	$(MAKE) shared-clean rc-clean httpd-clean
	# Also configure kernel
	$(MAKE) k$@

kconf:
	$(MAKE) -C $(LINUXDIR) config

kmconf:
	$(MAKE) -C $(LINUXDIR) menuconfig

koldconf: $(LINUXDIR)/.config
	$(MAKE) -C $(LINUXDIR) oldconfig

$(LINUXDIR)/include/linux/version.h: $(LINUXDIR)/.config
	$(MAKE) -C $(LINUXDIR) include/linux/version.h

# Convenience
config: conf

menuconfig: mconf

oldconfig: oldconf

# Default configurations
.config:
	cp config/defconfig $@
	$(MAKE) oldconfig

$(LINUXDIR)/.config: .config
	cp $(LINUXDIR)/arch/mips/defconfig-bcm947xx $@
	$(call SwitchConfParam,$@,CONFIG_IPV6,$(if $(CONFIG_IPV6),y,n))

#
# Overrides
#

httpd: netconf shared nvram $(EXTRA_LIBS)

rc: netconf shared nvram $(EXTRA_LIBS)
	$(MAKE) -C $@ GLOBAL_OPTIONS="$(GLOBAL_OPTIONS) -DMODEL_$(shell echo $(MODEL) | tr '[a-z]' '[A-Z]')" EXTRACFLAGS="$(EXTRACFLAGS)"

rc-install:
	$(MAKE) -C rc install INSTALLDIR=$(INSTALLDIR)/rc GLOBAL_OPTIONS="$(GLOBAL_OPTIONS) -DMODEL_$(shell echo $(MODEL) | tr '[a-z]' '[A-Z]')" EXTRACFLAGS="$(EXTRACFLAGS)"

www-%:
	$(MAKE) -C www $* INSTALLDIR=$(INSTALLDIR)/www

radvd/Makefile: radvd/Makefile.in
	cd radvd && CFLAGS="-g -Os" CPPFLAGS="$(EXTRACFLAGS)" \
	$(CONFIGURE) --prefix=""

radvd: radvd/Makefile

radvd-install:
	install -D radvd/radvd $(INSTALLDIR)/radvd/usr/sbin/radvd
	$(STRIP) $(INSTALLDIR)/radvd/usr/sbin/radvd

bridge/Makefile: bridge/Makefile.in
	cd bridge && CFLAGS="-g -Os $(EXTRACFLAGS)" \
	$(CONFIGURE) --prefix="/usr" --with-linux-headers=$(LINUXDIR)/include

bridge: bridge/Makefile

bridge-install: bridge
	install -D bridge/brctl/brctl $(INSTALLDIR)/bridge/usr/sbin/brctl
	$(STRIP) $(INSTALLDIR)/bridge/usr/sbin/brctl

ez-ipupdate/Makefile: ez-ipupdate/Makefile.in ez-ipupdate/config.h.in ez-ipupdate/configure.in
	cd ez-ipupdate && ac_cv_prog_CC=$(CC) CPP=$(CC) CFLAGS="-g -Os $(EXTRACFLAGS)" \
	$(CONFIGURE)

ez-ipupdate: ez-ipupdate/Makefile

ez-ipupdate-install:
	install -D ez-ipupdate/ez-ipupdate $(INSTALLDIR)/ez-ipupdate/usr/sbin/ez-ipupdate
	$(STRIP) $(INSTALLDIR)/ez-ipupdate/usr/sbin/ez-ipupdate

inadyn/Makefile.in: inadyn/Makefile.am inadyn/configure.ac
	NOCONFIGURE="yes" inadyn/autogen.sh

inadyn/Makefile: inadyn/Makefile.in inadyn/configure
	cd inadyn && CFLAGS="-g -Os $(EXTRACFLAGS)" \
	ac_cv_func_malloc_0_nonnull="yes" ac_cv_func_realloc_0_nonnull="yes" \
	use_cache_file="yes" \
	$(CONFIGURE)

inadyn: inadyn/Makefile

inadyn-install:
	install -D inadyn/src/inadyn $(INSTALLDIR)/inadyn/usr/sbin/inadyn
	$(STRIP) $(INSTALLDIR)/inadyn/usr/sbin/inadyn

bpalogin/Makefile: bpalogin/Makefile.in
	cd bpalogin && CC=$(CC) CFLAGS="-g -Os $(EXTRACFLAGS)" \
	$(CONFIGURE) --prefix=/usr

bpalogin: bpalogin/Makefile

bpalogin-install:
	install -D bpalogin/bpalogin $(INSTALLDIR)/bpalogin/usr/sbin/bpalogin
	$(STRIP) $(INSTALLDIR)/bpalogin/usr/sbin/bpalogin

busybox/.config: .config
	cp -fp busybox/sysdeps/linux/$(CONFIG_BUSYBOX_CONFIG) $@
	$(call SwitchConfParam,$@,CONFIG_FEATURE_IPV6 CONFIG_PING6 CONFIG_TRACEROUTE6,$(if $(CONFIG_IPV6),y,n))
	$(call SwitchConfParam,$@,CONFIG_SENDMAIL,$(if $(CONFIG_SENDMAIL),y,n))
	$(MAKE) -C busybox oldconfig

busybox: busybox/.config
	$(MAKE) -C $@ all STRIP=$(STRIP) EXTRA_CFLAGS="$(EXTRACFLAGS)" EXTRA_LDFLAGS="-Wl,-rpath /lib"

busybox-install: busybox
	$(MAKE) -C busybox install STRIP=$(STRIP) CONFIG_PREFIX=$(INSTALLDIR)/busybox EXTRA_CFLAGS="$(EXTRACFLAGS)" EXTRA_LDFLAGS="-Wl,-rpath /lib"

cdma:
	@true

cdma-install:
	install -d $(INSTALLDIR)/cdma
	$(MAKE) -C cdma install


iptables: $(LINUXDIR)/include/linux/version.h
	$(MAKE) -C $@ BINDIR=/usr/sbin LIBDIR=/usr/lib KERNEL_DIR=$(LINUXDIR) COPT_FLAGS="-Os $(EXTRACFLAGS)" EXTRA_LDFLAGS="-Wl,-rpath /lib" DO_MULTI=1

iptables-install: iptables
ifeq ($(CONFIG_IPTABLES),y)
	install -d $(INSTALLDIR)/iptables/usr/lib/iptables
	install iptables/extensions/libipt_*.so $(INSTALLDIR)/iptables/usr/lib/iptables
	install -D iptables/iptables $(INSTALLDIR)/iptables/usr/sbin/iptables
	$(STRIP) $(INSTALLDIR)/iptables/usr/sbin/iptables
	ln -sf iptables $(INSTALLDIR)/iptables/usr/sbin/iptables-restore
	ln -sf iptables $(INSTALLDIR)/iptables/usr/sbin/iptables-save
ifeq ($(CONFIG_IPV6),y)
	install iptables/extensions/libip6t_*.so $(INSTALLDIR)/iptables/usr/lib/iptables
	install iptables/ip6tables $(INSTALLDIR)/iptables/usr/sbin/ip6tables
	$(STRIP) $(INSTALLDIR)/iptables/usr/sbin/ip6tables
	ln -sf ip6tables $(INSTALLDIR)/iptables/usr/sbin/ip6tables-restore
	ln -sf ip6tables $(INSTALLDIR)/iptables/usr/sbin/ip6tables-save
endif
	$(STRIP) $(INSTALLDIR)/iptables/usr/lib/iptables/libip*.so
else
	# So that generic rule does not take precedence
	@true
endif

iptables-clean:
	-$(MAKE) -C iptables KERNEL_DIR=$(LINUXDIR) clean


netconf: iptables

upnp: netconf nvram shared

miniupnpd: iptables
	@true

wlconf: nvram shared

pptp-install: pptp
	install -D pptp/pptp $(INSTALLDIR)/pptp/usr/sbin/pptp
	$(STRIP) $(INSTALLDIR)/pptp/usr/sbin/pptp

ppp/Makefile: ppp/linux/Makefile.top
	cd ppp && $(CONFIGURE) --prefix=/usr --sysconfdir=/tmp

ppp: ppp/Makefile
	$(MAKE) -C $@ MFLAGS="$(if $(CONFIG_IPV6),HAVE_INET6=y,) EXTRACFLAGS=\"$(EXTRACFLAGS)\" EXTRA_LDFLAGS=\"-Wl,-rpath /lib\""

ppp-install: ppp
	install -D ppp/pppd/pppd $(INSTALLDIR)/ppp/usr/sbin/pppd
	$(STRIP) $(INSTALLDIR)/ppp/usr/sbin/pppd
	install -D ppp/chat/chat $(INSTALLDIR)/ppp/usr/sbin/chat
	$(STRIP) $(INSTALLDIR)/ppp/usr/sbin/chat
	install -D ppp/pppd/plugins/pppol2tp/pppol2tp.so $(INSTALLDIR)/ppp/usr/lib/pppd/pppol2tp.so
	$(STRIP) $(INSTALLDIR)/ppp/usr/lib/pppd/*.so

rp-pppoe/src/Makefile: rp-pppoe/src/Makefile.in
	cd rp-pppoe/src && CFLAGS="-g -O2 $(EXTRACFLAGS)" \
	    $(CONFIGURE) --prefix=/usr --enable-plugin=$(TOP)/ppp \
	     ac_cv_linux_kernel_pppoe=yes rpppoe_cv_pack_bitfields=rev

rp-pppoe: ppp rp-pppoe/src/Makefile
	$(MAKE) -C rp-pppoe/src pppoe-relay rp-pppoe.so

rp-pppoe-clean:
	$(MAKE) -C rp-pppoe/src clean

rp-pppoe-install:
	install -D rp-pppoe/src/pppoe-relay $(INSTALLDIR)/rp-pppoe/usr/sbin/pppoe-relay
	$(STRIP) $(INSTALLDIR)/rp-pppoe/usr/sbin/pppoe-relay
	install -D rp-pppoe/src/rp-pppoe.so $(INSTALLDIR)/rp-pppoe/usr/lib/pppd/rp-pppoe.so
	$(STRIP) $(INSTALLDIR)/rp-pppoe/usr/lib/pppd/rp-pppoe.so

accel-pptp: ppp accel-pptp/pppd_plugin/Makefile
	$(MAKE) -C accel-pptp/pppd_plugin

accel-pptp/pppd_plugin/Makefile: accel-pptp/pppd_plugin/Makefile.in $(LINUXDIR)/include/linux/version.h
	cd accel-pptp/pppd_plugin && CFLAGS="-g -O2 $(EXTRACFLAGS)" \
	    $(CONFIGURE) --prefix=/usr KDIR=$(LINUXDIR) PPPDIR=$(TOP)/ppp

accel-pptp-clean:
	$(MAKE) -C accel-pptp/pppd_plugin clean

accel-pptp-install: accel-pptp
	install -D accel-pptp/pppd_plugin/src/.libs/pptp.so $(INSTALLDIR)/accel-pptp/usr/lib/pppd/pptp.so
	$(STRIP) $(INSTALLDIR)/accel-pptp/usr/lib/pppd/pptp.so

dnsmasq:
	$(MAKE) -C $@ CFLAGS="-Os $(EXTRACFLAGS)" COPTS="$(if $(CONFIG_IPV6),-DUSE_IPV6,)"

dnsmasq-install:
	install -D dnsmasq/src/dnsmasq $(INSTALLDIR)/dnsmasq/usr/sbin/dnsmasq
	$(STRIP) $(INSTALLDIR)/dnsmasq/usr/sbin/dnsmasq

dropbear/config.h: dropbear/config.h.in
	cd dropbear && CPPFLAGS="-DARGTYPE=3 $(EXTRACFLAGS)" \
	    LDFLAGS="-Wl,-rpath /lib" \
	    $(CONFIGURE) --disable-zlib --disable-shadow \
	    --disable-lastlog --disable-utmp --disable-utmpx \
	    --disable-wtmp --disable-wtmpx \
	    --disable-libutil --disable-loginfunc --disable-pututline \
	    --disable-pututxline

dropbear: dropbear/config.h
	$(MAKE) -C $@ PROGRAMS="dropbear dbclient scp dropbearkey dropbearconvert" MULTI=1 SCPPROGRESS=1

dropbear-install:
	install -D dropbear/dropbearmulti $(INSTALLDIR)/dropbear/usr/sbin/dropbear
	$(STRIP) $(INSTALLDIR)/dropbear/usr/sbin/dropbear
	ln -sf dropbear $(INSTALLDIR)/dropbear/usr/sbin/dropbearkey
	ln -sf dropbear $(INSTALLDIR)/dropbear/usr/sbin/dropbearconvert
	install -d $(INSTALLDIR)/dropbear/usr/bin
	ln -sf ../sbin/dropbear $(INSTALLDIR)/dropbear/usr/bin/ssh
	ln -sf ../sbin/dropbear $(INSTALLDIR)/dropbear/usr/bin/scp

p910nd:
	$(MAKE) -C $@ p910nd CROSS=$(CROSS_COMPILE) CFLAGS="-DLOCKFILE_DIR=\\\"/var/lock\\\" -O2 $(EXTRACFLAGS)"

p910nd-install:
	install -D p910nd/p910nd $(INSTALLDIR)/p910nd/usr/sbin/p910nd
	$(STRIP) $(INSTALLDIR)/p910nd/usr/sbin/p910nd

samba/source/Makefile: samba/source/Makefile.in
	cd samba/source && \
	    CPPFLAGS="-D_GNU_SOURCE -DNDEBUG -DSHMEM_SIZE=524288 -Dfcntl=fcntl64" CFLAGS="-Os $(EXTRACFLAGS)" \
	    ac_cv_sizeof_int=4 ac_cv_sizeof_long=4 ac_cv_sizeof_short=2 \
	    samba_cv_FTRUNCATE_NEEDS_ROOT=no samba_cv_HAVE_BROKEN_FCNTL64_LOCKS=no \
	    samba_cv_HAVE_BROKEN_GETGROUPS=no samba_cv_HAVE_BROKEN_READDIR=no \
	    samba_cv_HAVE_FCNTL_LOCK=yes samba_cv_HAVE_FNMATCH=yes \
	    samba_cv_HAVE_FTRUNCATE_EXTEND=yes samba_cv_HAVE_IFACE_AIX=no \
	    samba_cv_HAVE_IFACE_IFCONF=yes samba_cv_HAVE_IFACE_IFREQ=yes \
	    samba_cv_HAVE_INO64_T=yes samba_cv_HAVE_IRIX_SPECIFIC_CAPABILITIES=no \
	    samba_cv_HAVE_OFF64_T=yes samba_cv_HAVE_ROOT=yes \
	    samba_cv_HAVE_SECURE_MKSTEMP=yes samba_cv_HAVE_SHARED_MMAP=yes \
	    samba_cv_HAVE_STRUCT_FLOCK64=yes samba_cv_HAVE_SYSV_IPC=no \
	    samba_cv_HAVE_TRUNCATED_SALT=no samba_cv_HAVE_UNION_SEMUN=no \
	    samba_cv_HAVE_UNSIGNED_CHAR=yes samba_cv_NEED_SGI_SEMUN_HACK=no \
	    samba_cv_REPLACE_INET_NTOA=no samba_cv_SIZEOF_INO_T=4 \
	    samba_cv_SIZEOF_OFF_T=4 samba_cv_SYSCONF_SC_NGROUPS_MAX=yes \
	    samba_cv_USE_SETRESUID=no samba_cv_USE_SETREUID=yes \
	    samba_cv_USE_SETEUID=yes samba_cv_USE_SETUIDX=no \
	    samba_cv_have_longlong=yes samba_cv_have_setresgid=no \
	    samba_cv_have_setresuid=no samba_cv_HAVE_GETTIMEOFDAY_TZ=yes \
	 $(CONFIGURE) --prefix=/usr --localstatedir=/var/log --libdir=/etc \
	    --with-privatedir=/etc --with-lockdir=/var/lock --with-syslog

samba: samba/source/Makefile
	$(MAKE) -C samba/source shared

samba-install:
	install -D samba/source/bin/smbd.shared $(INSTALLDIR)/samba/usr/sbin/smbd
	install -D samba/source/bin/nmbd.shared $(INSTALLDIR)/samba/usr/sbin/nmbd
	install -D samba/source/bin/smbpasswd.shared $(INSTALLDIR)/samba/usr/bin/smbpasswd
	install -D samba/source/bin/libsmb.so $(INSTALLDIR)/samba/usr/lib/libsmb.so
	install -d $(INSTALLDIR)/samba/usr/codepages/
	install -D -m 0644 samba/source/codepages/codepage.* $(INSTALLDIR)/samba/usr/codepages
	install -D -m 0644 samba/source/codepages/unicode_map.* $(INSTALLDIR)/samba/usr/codepages
	$(STRIP) $(INSTALLDIR)/samba/usr/sbin/smbd
	$(STRIP) $(INSTALLDIR)/samba/usr/sbin/nmbd
	$(STRIP) $(INSTALLDIR)/samba/usr/bin/smbpasswd
	$(STRIP) $(INSTALLDIR)/samba/usr/lib/libsmb.so

samba-clean:
	$(MAKE) -C samba/source clean

nfs-utils/Makefile: nfs-utils/Makefile.in
	cd nfs-utils && CPPFLAGS="$(EXTRACFLAGS)" knfsd_cv_bsd_signals=no \
	$(CONFIGURE) --enable-nfsv3 --disable-nfsv4 \
	    --disable-gss --disable-rquotad

nfs-utils: nfs-utils/Makefile
	$(MAKE) -C $@

nfs-utils-install:
	install -D nfs-utils/utils/nfsd/nfsd $(INSTALLDIR)/nfs-utils/usr/sbin/nfsd
	install -D nfs-utils/utils/mountd/mountd $(INSTALLDIR)/nfs-utils/usr/sbin/mountd
	install -D nfs-utils/utils/lockd/lockd $(INSTALLDIR)/nfs-utils/usr/sbin/lockd
	install -D nfs-utils/utils/exportfs/exportfs $(INSTALLDIR)/nfs-utils/usr/sbin/exportfs
	install -D nfs-utils/utils/showmount/showmount $(INSTALLDIR)/nfs-utils/usr/sbin/showmount
	install -D nfs-utils/utils/statd/statd $(INSTALLDIR)/nfs-utils/usr/sbin/statd
	install -D nfs-utils/support/lib/libnfs.so $(INSTALLDIR)/nfs-utils/usr/lib/libnfs.so
	$(STRIP) $(INSTALLDIR)/nfs-utils/usr/sbin/* $(INSTALLDIR)/nfs-utils/usr/lib/libnfs.so

portmap-install:
	install -D portmap/portmap $(INSTALLDIR)/portmap/usr/sbin/portmap
	$(STRIP) $(INSTALLDIR)/portmap/usr/sbin/portmap

iproute2: $(LINUXDIR)/include/linux/version.h
	$(MAKE) -C $@ KERNEL_INCLUDE=$(LINUXDIR)/include EXTRACFLAGS="-Os $(EXTRACFLAGS)" EXTRA_LDFLAGS="-Wl,-rpath /lib"

iproute2-install:
	install -D iproute2/ip/ip $(INSTALLDIR)/iproute2/usr/sbin/ip
	install -D iproute2/tc/tc $(INSTALLDIR)/iproute2/usr/sbin/tc
	$(STRIP) $(INSTALLDIR)/iproute2/usr/sbin/ip
	$(STRIP) $(INSTALLDIR)/iproute2/usr/sbin/tc

ucd-snmp/Makefile: ucd-snmp/Makefile.in
	cd ucd-snmp && \
	    ac_cv_CAN_USE_SYSCTL=no ac_cv_struct_ifnet_has_if_obytes=yes \
	    ac_cv_struct_ifnet_has_if_ibytes=yes ac_cv_struct_ifnet_has_if_ibytes=yes \
	 $(CONFIGURE) --with-cflags="-g -O2 $(EXTRACFLAGS)" \
	    --disable-debugging --without-opaque-special-types \
	    --with-out-mib-modules="v2party" --with-sys-location=Unknown --with-sys-contact=Administrator \
	    --with-logfile=/var/log/snmpd.log

ucd-snmp: ucd-snmp/Makefile

ucd-snmp-install:
	install -D ucd-snmp/agent/snmpd $(INSTALLDIR)/ucd-snmp/usr/sbin/snmpd
	$(STRIP) $(INSTALLDIR)/ucd-snmp/usr/sbin/snmpd

utils: shared

rp-l2tp/Makefile: rp-l2tp/Makefile.in
	cd rp-l2tp && CFLAGS="-g -O2 $(EXTRACFLAGS)" \
	$(CONFIGURE) --prefix=/usr --sysconfdir=/etc

rp-l2tp: ppp rp-l2tp/Makefile

rp-l2tp-install:
	install -D rp-l2tp/l2tpd $(INSTALLDIR)/rp-l2tp/usr/sbin/l2tpd
	$(STRIP) $(INSTALLDIR)/rp-l2tp/usr/sbin/l2tpd
	install -D rp-l2tp/handlers/l2tp-control $(INSTALLDIR)/rp-l2tp/usr/sbin/l2tp-control
	$(STRIP) $(INSTALLDIR)/rp-l2tp/usr/sbin/l2tp-control
	install -d $(INSTALLDIR)/rp-l2tp/usr/lib/l2tp/plugins
	install -D rp-l2tp/handlers/*.so $(INSTALLDIR)/rp-l2tp/usr/lib/l2tp/plugins
	$(STRIP) $(INSTALLDIR)/rp-l2tp/usr/lib/l2tp/plugins/*.so

xl2tpd: ppp
	CFLAGS="-g -O2 $(EXTRACFLAGS)" \
	$(MAKE) -C $@ xl2tpd PREFIX=/usr

xl2tpd-install:
	install -D xl2tpd/xl2tpd $(INSTALLDIR)/xl2tpd/usr/sbin/xl2tpd
	$(STRIP) $(INSTALLDIR)/xl2tpd/usr/sbin/xl2tpd

igmpproxy/src/Makefile: igmpproxy/src/Makefile.in
	cd igmpproxy && CPPFLAGS="$(EXTRACFLAGS)" \
	$(CONFIGURE) --prefix=/usr

igmpproxy: igmpproxy/src/Makefile
	$(MAKE) -C igmpproxy/src

igmpproxy-clean:
	$(MAKE) -C igmpproxy/src clean

igmpproxy-install:
	install -D igmpproxy/src/igmpproxy $(INSTALLDIR)/igmpproxy/usr/sbin/igmpproxy
	$(STRIP) $(INSTALLDIR)/igmpproxy/usr/sbin/igmpproxy

vsftpd:
	$(MAKE) -C $@ LDFLAGS="-Wl,-rpath /lib"

vsftpd-install:
	install -D vsftpd/vsftpd $(INSTALLDIR)/vsftpd/usr/sbin/vsftpd
	$(STRIP) $(INSTALLDIR)/vsftpd/usr/sbin/vsftpd

udpxy:
	$(MAKE) -C $@ release CDEFS="-O2 $(EXTRACFLAGS)"

udpxy-install:
	install -D udpxy/udpxy $(INSTALLDIR)/udpxy/usr/sbin/udpxy
	$(STRIP) $(INSTALLDIR)/udpxy/usr/sbin/udpxy
	ln -sf udpxy $(INSTALLDIR)/udpxy/usr/sbin/udpxrec

scsi-idle-install:
	install -D scsi-idle/scsi-start $(INSTALLDIR)/scsi-idle/usr/sbin/scsi-start
	$(STRIP) $(INSTALLDIR)/scsi-idle/usr/sbin/scsi-start
	ln -sf scsi-start $(INSTALLDIR)/scsi-idle/usr/sbin/scsi-stop

libusb10/Makefile: libusb10/Makefile.in
	cd libusb10 && CFLAGS="-O2 $(EXTRACFLAGS)" \
	$(CONFIGURE) --prefix=/usr ac_cv_lib_rt_clock_gettime=no

libusb10: libusb10/Makefile
	$(MAKE) -C $@

libusb/Makefile: libusb/Makefile.in
	cd libusb && CFLAGS="-Wall -Os $(EXTRACFLAGS)" \
	$(CONFIGURE) --prefix=/usr \
	    LIBUSB_1_0_CFLAGS="-I$(TOP)/libusb10/libusb" \
	    LIBUSB_1_0_LIBS="-L$(TOP)/libusb10/libusb/.libs -lusb-1.0"

libusb: libusb10 libusb/Makefile
	$(MAKE) -C $@

libusb-install:
	install -D libusb/libusb/.libs/libusb-0.1.so $(INSTALLDIR)/libusb/usr/lib/libusb-0.1.so
	$(STRIP) $(INSTALLDIR)/libusb/usr/lib/*.so

libusb10-install:
	install -D libusb10/libusb/.libs/libusb-1.0.so $(INSTALLDIR)/libusb10/usr/lib/libusb-1.0.so
	$(STRIP) $(INSTALLDIR)/libusb10/usr/lib/*.so

usb_modeswitch: libusb10
	$(MAKE) -C $@ CC=$(CC) CFLAGS="-Wall -Os $(EXTRACFLAGS) \
	    -I$(TOP)/libusb10/libusb -L$(TOP)/libusb10/libusb/.libs -lusb-1.0"

usb_modeswitch-install:
	install -D usb_modeswitch/usb_modeswitch $(INSTALLDIR)/usb_modeswitch/usr/sbin/usb_modeswitch
	$(STRIP) $(INSTALLDIR)/usb_modeswitch/usr/sbin/usb_modeswitch
	install -d $(INSTALLDIR)/usb_modeswitch/usr/share/usb_modeswitch.d/
	install -D -m 0644 usb_modeswitch/data/usb_modeswitch.d/* $(INSTALLDIR)/usb_modeswitch/usr/share/usb_modeswitch.d/

madwimax/Makefile: madwimax/Makefile.in
	cd madwimax && CPPFLAGS="$(EXTRACFLAGS)" PKG_CONFIG=/bin/true \
	    libusb1_CFLAGS="-I$(TOP)/libusb10/libusb" \
	    libusb1_LIBS="-L$(TOP)/libusb10/libusb/.libs -lusb-1.0" \
	$(CONFIGURE) --prefix=/usr --without-man-pages --with-script=wl500g --sysconfdir=/etc

madwimax: libusb10 madwimax/Makefile
	$(MAKE) -C $@

madwimax-install:
	install -D madwimax/src/madwimax $(INSTALLDIR)/madwimax/usr/sbin/madwimax
	$(STRIP) $(INSTALLDIR)/madwimax/usr/sbin/madwimax

lltd: nvram shared
	$(MAKE) -C $@ EXTRACFLAGS="$(EXTRACFLAGS)"

lltd-install: lltd
	install -D lltd/lld2d $(INSTALLDIR)/lltd/usr/sbin/lld2d
	$(STRIP) $(INSTALLDIR)/lltd/usr/sbin/lld2d
	install -D -m 0644 lltd/lld2d.conf $(INSTALLDIR)/lltd/usr/etc/lld2d.conf
	[ ! -f lltd/icons/$(MODEL).ico ] || \
	    install -D -m 0644 lltd/icons/$(MODEL).ico $(INSTALLDIR)/lltd/usr/share/lld2d/icon.ico

emf:
	$(MAKE) -C $(SRCBASE)/emf/emfconf CROSS=$(CROSS_COMPILE) EXTRACFLAGS="$(EXTRACFLAGS)"

emf-install:
	$(MAKE) -C $(SRCBASE)/emf/emfconf INSTALLDIR=$(INSTALLDIR) install

igs:
	$(MAKE) -C $(SRCBASE)/emf/igsconf CROSS=$(CROSS_COMPILE) EXTRACFLAGS="$(EXTRACFLAGS)"

igs-install:
	$(MAKE) -C $(SRCBASE)/emf/igsconf INSTALLDIR=$(INSTALLDIR) install

rcamdmips:
	$(MAKE) -C $@ LINUXKERNELSRC=$(LINUXDIR) EXTRACFLAGS="$(EXTRACFLAGS)"

LPRng/Makefile: LPRng/Makefile.in
	cd LPRng && CC=$(CC) CPPFLAGS="$(EXTRACFLAGS) -DWINDOW_1 -DTEST_WRITE -DNODEBUG -DLPR_with_ASUS" \
	$(CONFIGURE) --includedir=$(LINUXDIR)/include --disable-werror \
	--disable-kerberos --disable-ssl --disable-mit_kerberos4 \
	--with-userid=root --with-groupid=root --disable-setuid --disable-nls \
	--enable-static

LPRng: LPRng/Makefile
	$(MAKE) -C $@/src TARGET=lpd

LPRng-install:
	install -D LPRng/src/lpd $(INSTALLDIR)/LPRng/usr/sbin/lpd
	$(STRIP) $(INSTALLDIR)/LPRng/usr/sbin/lpd


image-%:
	$(MAKE) rc MODEL="$*"
	$(MAKE) package-$* MODEL="$*"

images-%:
	make image-$* LANGUAGE="EN"
	#make image-$* LANGUAGE="KR"
	#make image-$* LANGUAGE="TW"
	#make image-$* LANGUAGE="CN"
	#make image-$* LANGUAGE="JP"

images:
	make images-WL500gx
	make images-WL550gE
	make images-WL320gE
	make images-WL320gP
	make images-WL500gp
	make images-WL500W
	make images-WL520gu
	make images-WL500gpv2
	make images-WL330gE
	make images-WL700g

#
# Generic rules
#

%:
	[ ! -d $* ] || $(MAKE) -C $*  EXTRACFLAGS="$(EXTRACFLAGS)"

%-clean:
	[ ! -d $* ] || $(MAKE) -C $* clean

%-install:
	[ ! -d $* ] || $(MAKE) -C $* install INSTALLDIR=$(INSTALLDIR)/$*

$(obj-y) $(obj-n) $(obj-clean) $(obj-install): dummy

.PHONY: all clean distclean mrproper install package
.PHONY: conf mconf oldconf kconf kmconf config menuconfig oldconfig
.PHONY: mksquashfs-lzma
.PHONY: dummy
