#!/bin/sh
WANNO_1=0
WANNO_2=1
PINGCOUNT=5
SLEEP=$(expr $(nvram get backup_time) \* 60)
PINGADDR1=$(nvram get backup_testip1)
PINGADDR2=$(nvram get backup_testip2)

pingtest() {
  if [ $DEVDOWN = 0 ]; then
    route add $PINGADDR gw $GW
    if [ $? = 0 ]; then
      ping -c $PINGCOUNT $PINGADDR>/dev/null
      DEV=$?
      route del $PINGADDR
    else
      DEV=1
    fi
  else
    DEV=1
  fi
}

wan_pri="$(nvram get wan_backup_pri)"
wan_akt=0

wan1_ifname="$(nvram get wan"$WANNO_1"_ifname)"
wan2_ifname="$(nvram get wan"$WANNO_2"_ifname)"

if [ "$(nvram get wan"$WANNO_1"_proto)" = "pptp" -o \
     "$(nvram get wan"$WANNO_1"_proto)" = "pppoe" ]; then
  wan1_ifname="ppp0"
fi

if [ "$(nvram get wan"$WANNO_2"_proto)" = "pptp" -o \
     "$(nvram get wan"$WANNO_2"_proto)" = "pppoe" ]; then
  wan2_ifname="ppp0"
fi

echo $wan1_ifname x $wan2_ifname

if [ -z $wan_pri ]; then
  return
fi

route del $PINGADDR1 >/dev/null 2>/dev/null
route del $PINGADDR2 >/dev/null 2>/dev/null

while [ 1 ]; do
  wan_pri="$(nvram get wan_backup_pri)"
  ifconfig $wan1_ifname >/dev/null 2>/dev/null
  dev1_down=$?
  ifconfig $wan2_ifname >/dev/null 2>/dev/null
  dev2_down=$?

  DEVDOWN=$dev1_down
  PINGADDR=$PINGADDR1
  GW=$(nvram get wan${WANNO_1}_gateway)
  pingtest
  dev1=$DEV

  if [ $dev1 = 1 -a -n "$PINGADDR2" ]; then
   DEVDOWN=$dev1_down
   PINGADDR=$PINGADDR2
   GW=$(nvram get wan${WANNO_1}_gateway)
   pingtest
   dev1=$DEV
  fi

  sleep 10

  DEVDOWN=$dev2_down
  PINGADDR=$PINGADDR1
  GW=$(nvram get wan${WANNO_2}_gateway)
  pingtest
  dev2=$DEV

  if [ $dev2 = 1 -a -n "$PINGADDR2" ]; then
   DEVDOWN=$dev2_down
   PINGADDR=$PINGADDR2
   GW=$(nvram get wan${WANNO_2}_gateway)
   pingtest
   dev2=$DEV
  fi

  echo wan_pri=$wan_pri wan_akt=$wan_akt dev1_down=$dev1_down dev2_down=$dev2_down dev1=$dev1 dev2=$dev2

  if [ $dev1 = 0 -a $wan_pri = 1 -a $wan_akt != 1 \
   -o  $dev1 = 0 -a $dev2 != 0   -a $wan_akt != 1 ]; then
    echo Switch to $wan1_ifname
    wan_akt=1
    nvram set wan${WANNO_1}_primary=1
    nvram set wan${WANNO_2}_primary=0
    /usr/local/sbin/pre-backup $wan1_ifname $wan2_ifname
    wan-up $wan1_ifname
    /usr/local/sbin/post-backup $wan1_ifname $wan2_ifname
    logger WAN Switched to $wan1_ifname
  fi

  if [ $dev2 = 0 -a $wan_pri = 2 -a $wan_akt != 2 \
   -o  $dev2 = 0 -a $dev1 != 0   -a $wan_akt != 2 ]; then
    echo Switch to $wan2_ifname
    wan_akt=2
    nvram set wan${WANNO_1}_primary=0
    nvram set wan${WANNO_2}_primary=1
    /usr/local/sbin/pre-backup $wan2_ifname $wan1_ifname
    wan-up $wan2_ifname
    /usr/local/sbin/post-backup $wan2_ifname $wan1_ifname
    logger WAN Switched to $wan2_ifname
  fi

  sleep $SLEEP
done
