#!/bin/sh

ROOT_DIR=/usr

if [ "$(nvram get wan_modem_enable_x)" = "0" ]; then
 if [ -z "$(nvram get wan_modem_dial_first)" ]; then
   $(nvram set wan_modem_dial_first="1")
   exit
 fi
fi

if [ -z "$(nvram get wan_modem_enable_x)" ]; then
  nvram set wan_modem_enable_x=1
fi

if [ -n "$1" ]; then
  dialmode=$1
else
  dialmode="$(nvram get wan_modem_type)"
fi

if [ -z "$dialmode" ]; then
        dialmode="1"
fi

case "$dialmode" in
	0)	dialdir=$ROOT_DIR/ppp/uni
		;;
	1)	dialdir=$ROOT_DIR/ppp/uni
		;;
	3)	dialdir=$ROOT_DIR/ppp/dialup
		;;
	99)	dialdir=$ROOT_DIR/local/dial
		;;
	*)	echo Other
		;;
esac	

if [ ! -z $dialdir ]; then
#	cd $dialdir
#	./dial $dialmode $2
	source "$dialdir/dial"
fi
