#!/bin/sh

insmod usbserial
insmod zadacom.o

DEVNO=0
serialcomm /dev/usb/tts/0 ATZ|grep -q OK && DEVNO=0
serialcomm /dev/usb/tts/1 ATZ|grep -q OK && DEVNO=1
serialcomm /dev/usb/tts/2 ATZ|grep -q OK && DEVNO=2
export DEVNO

echo DEVNO=$DEVNO

while true; do
  kill -9 $(ps|grep pppd|grep zadacom|awk -F' ' '{print $1}') 2>/dev/null

  sleep 5

  if [ -z "$(nvram get zadacom_usbloc)" ]; then
   DEVICE="/dev/usb/tts/$DEVNO"
  else
   DEVICE=$(grep ": $(nvram get zadacom_usbloc) :" /proc/bus/usb/devpath | awk -F':' '{print $1}')
  fi

  export DEVICE

  IFNAME=$(nvram get wan0_modem_ifname)
  export IFNAME

  /usr/ppp/zadacom/update $1

  grep -q 'Vendor=0fce ProdID=d019' /proc/bus/usb/devices
  if [ $? = 0 ]; then
    exec zadacom2G/dial $1
  fi

  pppd call zadacom >> /tmp/chat.log

  sleep 25
done
              
