#!/bin/sh
nvram set ipw_stat_signal=---
nvram set ipw_stat_battery=---
nvram set ipw_stat_operator=---
nvram set ipw_stat_version=

if [ -z "$(grep "IPWireless Modem" /proc/bus/usb/devices)" ]; then
 nvram set ipw_stat_present=Nenalezen
 nvram set ipw_stat_connect=Nepřipojeno
else
 nvram set ipw_stat_present=Nalezen
 nvram set ipw_stat_connect=Připojuji
fi

