#!/bin/sh

insmod usbserial
insmod ipw.o

nvram set ipw_stat_pin=
nvram set ipw_stat_pin_lock=
/tmp/ppp/ipw/clearstat

while true; do
  kill -9 $(ps|grep pppd|grep ipw|awk -F' ' '{print $1}') 2>/dev/null

  sleep 5

  if [ -z "$(nvram get ipw_usbloc)" ]; then
   DEVICE="/dev/usb/tts/0"
  else
   DEVICE=$(grep ": $(nvram get ipw_usbloc) :" /proc/bus/usb/devpath | awk -F':' '{print $1}')
  fi

  export DEVICE
  
  IFNAME=$(nvram get wan0_modem_ifname)
  export IFNAME

  /usr/ppp/ipw/update $1

  /usr/ppp/ipw/clearstat

  pppd call ipw >> /tmp/chat.log

  sleep 25
done
              
