#!/bin/bash

echo "Preparing web interface..."

if [ -n "$1" ]; then

	TMPDIR=$1

	cp -af web web_$TMPDIR

	### 2. Removing IPV6 & WiMAX pages
	if [ "$CONFIG_IPV6" != "y" ]; then
		echo "Removing IPV6 pages..."
		rm -rf web_$TMPDIR/*IPV6*.asp
		sed -ri '/IPV6/d' web_$TMPDIR/index.js
	fi

	if [ "$CONFIG_LLTD" != "y" ]; then
		sed -ri '/LLTD responder/d' web_$TMPDIR/Advanced_Services_Content.asp
	fi

	if [ "$CONFIG_MADWIMAX" != "y" ]; then
		echo "Removing WiMax pages..."
		rm -rf web_$TMPDIR/*WiMax*.asp
		sed -ri '/WiMAX/d' web_$TMPDIR/index.js
		sed -ri '/WiMAX/d' web_$TMPDIR/Advanced_LANWAN_Content.asp
	fi

	if [ "$CONFIG_MODEM" != "y" ]; then
		echo "Removing 3G/cdma pages..."
		rm -f web_$TMPDIR/Main_ChatStatus_Content.asp
		rm -f web_$TMPDIR/Advanced_ConnectionMode_Content.asp
		rm -f web_$TMPDIR/Main_SysInfo_Content.asp
		sed -ri '/3G\/CDMA Modem/d;/Main_SysInfo_Content/d' web_$TMPDIR/index.js
		sed -ri '/usbmodem/d' web_$TMPDIR/Advanced_LANWAN_Content.asp
	fi

	if [ "$CONFIG_MADWIMAX" != "y" ] && [ "$CONFIG_MODEM" != "y" ]; then
		echo "Removing USB Modem submenu..."
		sed -ri '/USB Network Devices/d;/USBNetworkDevicesMenu_tmpl\.Asp/d' web_$TMPDIR/index.js
	elif [ "$CONFIG_MADWIMAX" = "y" ] && [ "$CONFIG_MODEM" != "y" ]; then
		sed -i 's/USBNetworkDevicesMenu_tmpl\.Asp/Advanced_WiMax_Content.asp/g' web_$TMPDIR/index.js
	elif [ "$CONFIG_MODEM" = "y" ]; then
		sed -i 's/USBNetworkDevicesMenu_tmpl\.Asp/Advanced_ConnectionMode_Content.asp/g' web_$TMPDIR/index.js
	fi

	if [ "$CONFIG_NTFS3G" != "y" ]; then
		sed -ri '/ntfs/d' web_$TMPDIR/Advanced_Services_Content.asp
	fi

	### 3. Strip *.asp, *.inc, *.css and *.js ###
	echo "Stripping web interface..."

	# Strip c++ style (//...) full line comments from js, asp and inc
	LIST=$(ls web_$TMPDIR/*.{js,asp,inc})
	PATTERN="s|^[ \t]*//.*$||"
	echo "sed $PATTERN"
	for i in $LIST; do
		sed -ri "$PATTERN" $i
	done

	# Strip the rest of c++ style (//...) comments from js only, however, preserve urls like http://
	LIST=$(ls web_$TMPDIR/*.js)
	PATTERN="s|[ \t]*[^:]//.*$||"
	echo "sed $PATTERN"
	for i in $LIST; do
		sed -ri "$PATTERN" $i
	done

	# Strip single and multilne /*...*/ comments
	LIST=$(ls web_$TMPDIR/*.{js,asp,inc,css})
	echo "Stripping JS comments..."
	for i in $LIST; do
		../remccoms2.sh $i
	done

	# Remove \r, trim each line from both sides, delete empty lines from asp, inc, css, js
	LIST=$(ls web_$TMPDIR/*.{asp,inc,css,js})
#	PATTERN="s/\x0D//g;s/[ \t]+/ /g;s/^[ \t]+//;s/[ \t]+$//;/^$/d"
	PATTERN="s/^[ \t]+//;s/[ \t\x0d]+$//;/^$/d"
	echo "sed $PATTERN"
	for i in $LIST; do
		sed -ri "$PATTERN" $i
	done

	LIST=$(ls web_$TMPDIR/*.{asp,inc})
	echo "Performing final processing of HTML..."
	for i in $LIST; do
# Remove single line HTML comments
		sed -ri 's|<!--.*-->||' $i
# Remove HTML pseudo-comments in <script> and <style> inclusions as they are anyway not everywhere
		sed -ri '/^<!--$/d;/^-->$/d' $i
# Remove junk from html headers
		sed -ri '/<meta http-equiv="Content-Type"/d' $i
		sed -ri '/<meta http-equiv="Content-Language" content="zh-tw">/d' $i
		sed -ri '/<meta name="GENERATOR" content="Microsoft FrontPage 4.0">/d' $i
		sed -ri '/<meta name="ProgId" content="FrontPage.Editor.Document">/d' $i
		sed -ri '/<meta name="VI60_defaultClientScript" content="JavaScript">/d' $i
# Add uniform Content-Type line to all .asp-s
		sed -ri 's|</title>|</title>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">|' $i
# Remove \n from the asp files in the following situation: ...>\n...
		sed -ri ':b;/>$/N;s/>\n/>/;tb' $i
# Remove \n from the asp files in the following situation: ...\n<...
		sed -ri ':c;$!N;s/\n</</;tc' $i
	done

	### 4. Copy different files for different Model ###
	
	if [ "$MODEL" = "WL330gE" ] || [ "$MODEL" = "WL320gE" ] \
		|| [ "$MODEL" = "WL320gP" ]; then
		cp -f web_$TMPDIR/Advanced_Wireless11g_Content.asp web_$TMPDIR/Advanced_Wireless_Content.asp
    		cp -f web_$TMPDIR/Advanced_ACL11g_Content.asp web_$TMPDIR/Advanced_ACL_Content.asp		
		cp -f web_$TMPDIR/Advanced_DMZIP11g_Content.asp web_$TMPDIR/Advanced_DMZIP_Content.asp

		cp -f web_$TMPDIR/Advanced_OperationMode_Content_300g.asp web_$TMPDIR/Advanced_OperationMode_Content.asp

		#cp -f web_$TMPDIR/Advanced_DDNS_Content_300g.asp web_$TMPDIR/Advanced_DDNS_Content.asp
		cp -f web_$TMPDIR/Main_WStatus11g_Content.asp web_$TMPDIR/Main_WStatus_Content.asp
		cp -f web_$TMPDIR/Main_Index_AccessPoint11g_300g.asp web_$TMPDIR/Main_Index_AccessPoint.asp
		cp -f web_$TMPDIR/Main_Index_HomeGateway11g_300g.asp web_$TMPDIR/Main_Index_HomeGateway.asp
		cp -f web_$TMPDIR/Main_Index_Router11g_300g.asp web_$TMPDIR/Main_Index_Router.asp
		cp -f web_$TMPDIR/Main_AStatus11g_Content.asp web_$TMPDIR/Main_AStatus_Content.asp
		cp -f web_$TMPDIR/Main_GStatus11g_Content.asp web_$TMPDIR/Main_GStatus_Content.asp
		cp -f web_$TMPDIR/Main_RStatus11g_Content.asp web_$TMPDIR/Main_RStatus_Content.asp		
		cp -f web_$TMPDIR/Advanced_Exposed_Content_SP.asp web_$TMPDIR/Advanced_Exposed_Content.asp
		
		### 4.2 web graph ###		
		cp -f web_$TMPDIR/graph/internet_all_300.gif web_$TMPDIR/graph/internet_all.gif
		cp -f web_$TMPDIR/graph/internet_none_300.gif web_$TMPDIR/graph/internet_none.gif
		cp -f web_$TMPDIR/graph/internet_some_300.gif web_$TMPDIR/graph/internet_some.gif			
		cp -f web_$TMPDIR/graph/wds_ap_300.gif web_$TMPDIR/graph/wds_ap.gif	
		cp -f web_$TMPDIR/graph/wds_mixed_connect_300.gif web_$TMPDIR/graph/wds_mixed_connect.gif
		cp -f web_$TMPDIR/graph/wds_mixed_anony_300.gif web_$TMPDIR/graph/wds_mixed_anony.gif
		cp -f web_$TMPDIR/graph/wds_mixed_both_300.gif web_$TMPDIR/graph/wds_mixed_both.gif
		cp -f web_$TMPDIR/graph/wds_wds_connect_300.gif web_$TMPDIR/graph/wds_wds_connect.gif
		cp -f web_$TMPDIR/graph/wds_wds_anony_300.gif web_$TMPDIR/graph/wds_wds_anony.gif
		cp -f web_$TMPDIR/graph/wds_wds_both_300.gif web_$TMPDIR/graph/wds_wds_both.gif			
		cp -f web_$TMPDIR/graph/wf_g_300.gif web_$TMPDIR/graph/wf_g.gif	
		cp -f web_$TMPDIR/graph/wf_none_300.gif web_$TMPDIR/graph/wf_none.gif	
		
	elif [ "$MODEL" = "WL500gx" ] || [ "$MODEL" = "WL500gp" ] \
		|| [ "$MODEL" = "WL500gpv2" ] || [ "$MODEL" = "WL700g" ] \
		|| [ "$MODEL" = "WL500W" ] || [ "$MODEL" = "RT-N16" ] \
		|| [ "$MODEL" = "RT-N15U" ] \
		|| [ "$MODEL" = "RT-N12" ] || [ "$MODEL" = "RT-N12B1" ] || [ "$MODEL" = "RT-N12C1" ] \
		|| [ "$MODEL" = "RT-N10" ] || [ "$MODEL" = "RT-N10U" ] \
		|| [ "$MODEL" = "WL550gE" ] || [ "$MODEL" = "WL520gu" ]; then						
		if [ "$MODEL" = "WL500W" ] || [ "$MODEL" = "RT-N16" ] \
		    || [ "$MODEL" = "RT-N15U" ] \
		    || [ "$MODEL" = "RT-N12" ] || [ "$MODEL" = "RT-N12B1" ] || [ "$MODEL" = "RT-N12C1" ] \
		    || [ "$MODEL" = "RT-N10" ] || [ "$MODEL" = "RT-N10U" ]; then
			cp -f web_$TMPDIR/Advanced_Wireless11n_Content.asp web_$TMPDIR/Advanced_Wireless_Content.asp
			cp -f web_$TMPDIR/Advanced_WAdvanced_Content_11n.asp web_$TMPDIR/Advanced_WAdvanced_Content.asp
		else
			cp -f web_$TMPDIR/Advanced_Wireless11g_Content.asp web_$TMPDIR/Advanced_Wireless_Content.asp
		fi
    		cp -f web_$TMPDIR/Advanced_ACL11g_Content.asp web_$TMPDIR/Advanced_ACL_Content.asp
		cp -f web_$TMPDIR/Advanced_DMZIP11g_Content.asp web_$TMPDIR/Advanced_DMZIP_Content.asp
		cp -f web_$TMPDIR/Main_WStatus11g_Content.asp web_$TMPDIR/Main_WStatus_Content.asp	
		cp -f web_$TMPDIR/Main_Index_AccessPoint11g.asp web_$TMPDIR/Main_Index_AccessPoint.asp
		cp -f web_$TMPDIR/Main_Index_HomeGateway11g.asp web_$TMPDIR/Main_Index_HomeGateway.asp
		cp -f web_$TMPDIR/Main_Index_Router11g.asp web_$TMPDIR/Main_Index_Router.asp
		### 4.2 web graph ###
		cp -f web_$TMPDIR/Advanced_Exposed_Content_SP.asp web_$TMPDIR/Advanced_Exposed_Content.asp

		cp -f web_$TMPDIR/graph/internet_all_500.gif ./web_$TMPDIR/graph/internet_all.gif
		cp -f web_$TMPDIR/graph/internet_none_500.gif ./web_$TMPDIR/graph/internet_none.gif
		cp -f web_$TMPDIR/graph/internet_some_500.gif ./web_$TMPDIR/graph/internet_some.gif			
		cp -f web_$TMPDIR/graph/wds_ap_500.gif ./web_$TMPDIR/graph/wds_ap.gif	
		cp -f web_$TMPDIR/graph/wds_mixed_connect_500.gif ./web_$TMPDIR/graph/wds_mixed_connect.gif
		cp -f web_$TMPDIR/graph/wds_mixed_anony_500.gif ./web_$TMPDIR/graph/wds_mixed_anony.gif
		cp -f web_$TMPDIR/graph/wds_mixed_both_500.gif ./web_$TMPDIR/graph/wds_mixed_both.gif
		cp -f web_$TMPDIR/graph/wds_wds_connect_500.gif ./web_$TMPDIR/graph/wds_wds_connect.gif
		cp -f web_$TMPDIR/graph/wds_wds_anony_500.gif ./web_$TMPDIR/graph/wds_wds_anony.gif
		cp -f web_$TMPDIR/graph/wds_wds_both_500.gif ./web_$TMPDIR/graph/wds_wds_both.gif			
		cp -f web_$TMPDIR/graph/wf_g_300.gif web_$TMPDIR/graph/wf_g.gif	
		cp -f web_$TMPDIR/graph/wf_none_300.gif web_$TMPDIR/graph/wf_none.gif

	fi

	### 5. Remove useless files in ./target/web/* ###
	rm -rf web_$TMPDIR/flash.default*
	rm -rf web_$TMPDIR/*11n*.asp
	rm -rf web_$TMPDIR/*11g*.asp
	rm -rf web_$TMPDIR/*11b*.asp
	rm -rf web_$TMPDIR/*_300g.asp	
	rm -rf web_$TMPDIR/*_SP.asp

	rm -rf web_$TMPDIR/*Certificate*.asp
	rm -rf web_$TMPDIR/*UniqueKey*.asp
	
	rm -rf web_$TMPDIR/graph/*_300.*
	rm -rf web_$TMPDIR/graph/*_500.*
	rm -rf web_$TMPDIR/graph/*_600.*
	rm -rf web_$TMPDIR/graph/*_500g.*
	rm -rf web_$TMPDIR/graph/*_500b.*
	rm -rf web_$TMPDIR/graph/*_300g.*
	rm -rf web_$TMPDIR/graph/*_500gx.*	
	rm -rf web_$TMPDIR/graph/*_520g.*
# CHUPA
	rm -rf web_$TMPDIR/graph/*_HDD.*
	rm -rf web_$TMPDIR/graph/*_550g.*
	rm -rf web_$TMPDIR/graph/*_500gp.*	
	rm -rf web_$TMPDIR/graph/!.gif
	rm -rf web_$TMPDIR/graph/AP.gif
	rm -rf web_$TMPDIR/graph/Connecting.gif
	rm -rf web_$TMPDIR/graph/Corner.gif
	rm -rf web_$TMPDIR/graph/Disconnect.gif
	rm -rf web_$TMPDIR/graph/Firewall.gif
	rm -rf web_$TMPDIR/graph/List_backgroup.gif
	rm -rf web_$TMPDIR/graph/Notebook.gif
	rm -rf web_$TMPDIR/graph/PC.gif
	rm -rf web_$TMPDIR/graph/V.gif
	rm -rf web_$TMPDIR/graph/apicon.gif
	rm -rf web_$TMPDIR/graph/apply.gif
	rm -rf web_$TMPDIR/graph/asusLogo.jpg
	rm -rf web_$TMPDIR/graph/delthisentry.gif
	rm -rf web_$TMPDIR/graph/iBox.gif
	rm -rf web_$TMPDIR/graph/internet.gif
	rm -rf web_$TMPDIR/graph/restore.gif
	rm -rf web_$TMPDIR/graph/sArrow.gif
	rm -rf web_$TMPDIR/graph/save.gif
	rm -rf web_$TMPDIR/graph/showroutingtable.gif
	rm -rf web_$TMPDIR/graph/start.gif
	rm -rf web_$TMPDIR/graph/sumhorsd.gif
	rm -rf web_$TMPDIR/graph/sumtextb.jpg
	rm -rf web_$TMPDIR/graph/x.gif

	rm -f web_$TMPDIR/graph/internet_*.gif
	rm -f web_$TMPDIR/graph/wf_both.gif
	rm -f web_$TMPDIR/graph/wf_none.gif
	rm -f web_$TMPDIR/graph/wf_[ag].gif
	
	rm -f web_$TMPDIR/graph/wds_*.gif 

	rm -f web_$TMPDIR/graph/many.gif
	
	rm -f web_$TMPDIR/Advanced_Authentication_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZDHCP_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZDLFilter_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZDWFilter_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZIP_Content.asp
	rm -f web_$TMPDIR/Advanced_DynamicRoute_Content.asp
	rm -f web_$TMPDIR/Advanced_FilterHelp_Widzard.asp
	rm -f web_$TMPDIR/Advanced_GRouterHelp_Widzard.asp
	rm -f web_$TMPDIR/Advanced_Help_Widzard.asp
	rm -f web_$TMPDIR/Advanced_LFirewall_Content.asp
	rm -f web_$TMPDIR/Advanced_MultiPPPoE_Content.asp
	rm -f web_$TMPDIR/Advanced_PortForwarding_Widzard.asp
	rm -f web_$TMPDIR/Advanced_PortMapping_Content.asp
	rm -f web_$TMPDIR/Advanced_PrinterSetup_Content.asp
	rm -f web_$TMPDIR/Advanced_PrinterSetup_Widzard.asp
	rm -f web_$TMPDIR/Advanced_RDHCP_Content.asp
	rm -f web_$TMPDIR/Advanced_RouterHelp_Widzard.asp
	rm -f web_$TMPDIR/Advanced_VirtualServer_Widzard.asp
	rm -f web_$TMPDIR/Advanced_WMMADV_Content.asp
	rm -f web_$TMPDIR/Basic_AOperation_Content.asp
	rm -f web_$TMPDIR/Basic_Operation_Content.asp
	rm -f web_$TMPDIR/Main_Content.asp
	rm -f web_$TMPDIR/Main_Index_Content.asp
	rm -f web_$TMPDIR/Main_Password_Content.asp
	rm -f web_$TMPDIR/Main_Status_Content.asp
			
# /CHUPA

else
	echo Usage: $0 tmpdir
fi

