#!/bin/bash

echo "Preparing $MODEL web interface..."

if [ -n "$1" ]; then

	TMPDIR=$1
	MODEL=$2

	cp -af web web_$TMPDIR

	### 2. Removing IPV6 & WiMAX pages
	if [ "$CONFIG_IPV6" != "y" ]; then
		echo "Removing IPV6 pages..."
		rm -rf web_$TMPDIR/*IPV6*.asp
		sed -ri '/IPV6/d' web_$TMPDIR/index.js
	fi

	if [ "$CONFIG_LLTD" != "y" ]; then
		sed -ri '/LLTD responder/d' web_$TMPDIR/Advanced_Services_Content.asp
	fi

	if [ "$CONFIG_MADWIMAX" != "y" ]; then
		echo "Removing WiMax pages..."
		rm -rf web_$TMPDIR/*WiMax*.asp
		sed -ri '/WiMAX/d' web_$TMPDIR/index.js
		sed -ri '/WiMAX/d' web_$TMPDIR/Advanced_WAN_Content.asp
	fi

	if [ "$CONFIG_MODEM" != "y" ]; then
		echo "Removing 3G/cdma pages..."
		rm -f web_$TMPDIR/Main_ChatStatus_Content.asp
		rm -f web_$TMPDIR/Advanced_ConnectionMode_Content.asp
		rm -f web_$TMPDIR/Main_SysInfo_Content.asp
		sed -ri '/3G\/CDMA Modem/d;/Main_SysInfo_Content/d' web_$TMPDIR/index.js
		sed -ri '/usbmodem/d' web_$TMPDIR/Advanced_WAN_Content.asp
	fi

	if [ "$CONFIG_MADWIMAX" != "y" ] && [ "$CONFIG_MODEM" != "y" ]; then
		echo "Removing USB Modem submenu..."
		sed -ri '/USB Network Devices/d;/USBNetworkDevicesMenu_tmpl\.Asp/d' web_$TMPDIR/index.js
	elif [ "$CONFIG_MADWIMAX" = "y" ] && [ "$CONFIG_MODEM" != "y" ]; then
		sed -i 's/USBNetworkDevicesMenu_tmpl\.Asp/Advanced_WiMax_Content.asp/g' web_$TMPDIR/index.js
	elif [ "$CONFIG_MODEM" = "y" ]; then
		sed -i 's/USBNetworkDevicesMenu_tmpl\.Asp/Advanced_ConnectionMode_Content.asp/g' web_$TMPDIR/index.js
	fi

	if [ "$CONFIG_NTFS3G" != "y" ]; then
		sed -ri '/ntfs/d' web_$TMPDIR/Advanced_Services_Content.asp
	fi

	### 3. Strip *.asp, *.inc, *.css and *.js ###
	echo "Stripping web interface..."

	# Strip c++ style (//...) full line comments from js, asp and inc
	LIST=$(ls web_$TMPDIR/*.{js,asp,inc})
	PATTERN="s|^[ \t]*//.*$||"
	echo "sed $PATTERN"
	for i in $LIST; do
		sed -ri "$PATTERN" $i
	done

	# Strip the rest of c++ style (//...) comments from js only, however, preserve urls like http://
	LIST=$(ls web_$TMPDIR/*.js)
	PATTERN="s|[ \t]*[^:]//.*$||"
	echo "sed $PATTERN"
	for i in $LIST; do
		sed -ri "$PATTERN" $i
	done

	# Strip single and multilne /*...*/ comments
	LIST=$(ls web_$TMPDIR/*.{js,asp,inc,css})
	echo "Stripping JS comments..."
	for i in $LIST; do
		./remccoms2.sh $i
	done

	# Remove \r, trim each line from both sides, delete empty lines from asp, inc, css, js
	LIST=$(ls web_$TMPDIR/*.{asp,inc,css,js})
#	PATTERN="s/\x0D//g;s/[ \t]+/ /g;s/^[ \t]+//;s/[ \t]+$//;/^$/d"
	PATTERN="s/^[ \t]+//;s/[ \t\x0d]+$//;/^$/d"
	echo "sed $PATTERN"
	for i in $LIST; do
		sed -ri "$PATTERN" $i
	done

	LIST=$(ls web_$TMPDIR/*.{asp,inc})
	echo "Performing final processing of HTML..."
	for i in $LIST; do
# Remove single line HTML comments
		sed -ri 's|<!--.*-->||' $i
# Remove HTML pseudo-comments in <script> and <style> inclusions as they are anyway not everywhere
		sed -ri '/^<!--$/d;/^-->$/d' $i
# Add uniform Content-Type line to all .asp-s
		sed -ri '/<meta http-equiv="Content-Type"/d' $i
		sed -ri 's|</title>|</title>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">|' $i
# Remove \n from the asp files in the following situation: ...>\n...
		sed -ri ':b;/>$/N;s/>\n/>/;tb' $i
# Remove \n from the asp files in the following situation: ...\n<...
		sed -ri ':c;$!N;s/\n</</;tc' $i
	done

	### 4. Copy different files for different Model ###
	if [ "$MODEL" = "WL500W" ] || [ "$MODEL" = "RT-N16" ] \
	    || [ "$MODEL" = "RT-N15U" ] \
	    || [ "$MODEL" = "RT-N12" ] || [ "$MODEL" = "RT-N12B1" ] || [ "$MODEL" = "RT-N12C1" ] \
	    || [ "$MODEL" = "RT-N10" ] || [ "$MODEL" = "RT-N10U" ]; then
		cp -f web_$TMPDIR/Advanced_Wireless_Content_11n.asp web_$TMPDIR/Advanced_Wireless_Content.asp
		cp -f web_$TMPDIR/Advanced_WAdvanced_Content_11n.asp web_$TMPDIR/Advanced_WAdvanced_Content.asp
	fi

	### 5. Remove useless files in ./target/web/* ###
	rm -rf web_$TMPDIR/*11n*.asp

# CHUPA
	rm -f web_$TMPDIR/graph/!.gif
	rm -f web_$TMPDIR/graph/V.gif
	rm -f web_$TMPDIR/graph/x.gif
	rm -f web_$TMPDIR/graph/Corner.gif
	rm -f web_$TMPDIR/graph/asusLogo.jpg

	rm -f web_$TMPDIR/Advanced_Authentication_Content.asp
	rm -f web_$TMPDIR/Advanced_WCertificate_Content.asp
	rm -f web_$TMPDIR/Advanced_UniqueKey_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZDHCP_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZDLFilter_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZDWFilter_Content.asp
	rm -f web_$TMPDIR/Advanced_DMZIP_Content.asp
	rm -f web_$TMPDIR/Advanced_DynamicRoute_Content.asp
	rm -f web_$TMPDIR/Advanced_FilterHelp_Widzard.asp
	rm -f web_$TMPDIR/Advanced_GRouterHelp_Widzard.asp
	rm -f web_$TMPDIR/Advanced_Help_Widzard.asp
	rm -f web_$TMPDIR/Advanced_LFirewall_Content.asp
	rm -f web_$TMPDIR/Advanced_MultiPPPoE_Content.asp
	rm -f web_$TMPDIR/Advanced_PortForwarding_Widzard.asp
	rm -f web_$TMPDIR/Advanced_PrinterSetup_Content.asp
	rm -f web_$TMPDIR/Advanced_PrinterSetup_Widzard.asp
	rm -f web_$TMPDIR/Advanced_RouterHelp_Widzard.asp
	rm -f web_$TMPDIR/Advanced_VirtualServer_Widzard.asp

	rm -f web_$TMPDIR/Basic_AOperation_Content.asp
	rm -f web_$TMPDIR/Basic_Operation_Content.asp
# /CHUPA

else
	echo Usage: $0 tmpdir
fi
