#!/bin/sh

FILE=usb_modeswitch.conf

if [ -n "$1" ]; then
  zerocddir=$1
else
  zerocddir="$(nvram get wan_modem_zerocd_mode)"
fi

if [ "${zerocddir}" == "UserDefined" ]; then
 zerocddir="/usr/local/etc"
else
 zerocddir="/usr/ppp/zerocdconf/${zerocddir}"
fi

[ -f "${zerocddir}/${FILE}" ] && usb_modeswitch -c ${zerocddir}/${FILE}
