#!/bin/sh

maxpacket=$(nvram get wan_modem_packetsize)
if [ -n "$maxpacketsize" -a "$maxpacketsize" != "0" ]; then
 maxpacket="maxSize=${maxpacketsize}"
else
 maxpacket=
fi

insmod acm $maxpacket

if [ "$(nvram get wan_modem_vid)" = "" -o "$(nvram get wan_modem_pid)" = "" ]; then
 insmod usbserial
else
 insmod usbserial vendor=$(nvram get wan_modem_vid) product=$(nvram get wan_modem_pid) $maxpacket
fi

insmod option
insmod pl2303
insmod ftdi_sio

while true; do
  kill -9 $(ps|grep pppd|grep dialup|awk -F' ' '{print $1}') 2>/dev/null

  sleep 5

  if [ -z "$(nvram get wan_modem_usbloc)" ]; then
   if [ -c /dev/usb/acm/0 ]; then
    DEVICE="/dev/usb/acm/0"
   else
    DEVICE="/dev/usb/tts/0"
   fi
  else
   DEVICE=$(grep ": $(nvram get wan_modem_usbloc) :" /proc/bus/usb/devpath | awk -F':' '{print $1}')
  fi

  export DEVICE
  
  IFNAME=$(nvram get wan0_pppoe_ifname)
  export IFNAME

  /usr/ppp/dialup/update $1

  pppd call dialup >> /tmp/chat.log

  sleep 25
done
