#!/bin/sh

USERNAME=$(nvram get wan_modem_username)
PASSWORD=$(nvram get wan_modem_password)
DIALNO=$(nvram get wan_modem_dialno)
INIT=$(nvram get wan_modem_dialup_init)
PORTSPEED=$(nvram get wan_modem_portspeed)

if [ $INIT != "" ]; then
 INIT="'OK' '$INIT'"
fi

echo $DEVICE > /tmp/ppp/peers/dialup
echo $PORTSPEED >> /tmp/ppp/peers/dialup
sed -e "s/\\\$username\\\$/$USERNAME/g" \
    -e "s/\\\$password\\\$/$PASSWORD/g" /usr/ppp/dialup/dialup >> /tmp/ppp/peers/dialup
echo $(nvram get wan_modem_param_$1) >> /tmp/ppp/peers/dialup

sed -e "s/\\\$dialno\\\$/$DIALNO/g" \
    -e "s/\\\$init\\\$/$INIT/g" -e "/^$/d" /usr/ppp/dialup/dialup.chat > /tmp/ppp/peers/dialup.chat
