#!/bin/sh
apn=$(nvram get wan_modem_apn)
dialnumber=$(nvram get wan_modem_dialno)
modem=$(nvram get wan_modem_standard) #1 - gprs/edge/umts/hsdpa, 0 - cdma/evdo
username=$(nvram get wan_modem_username)
port=$(nvram get wan_modem_tts_port)
portspeed=$(nvram get wan_modem_portspeed)
password=$(nvram get wan_modem_password)
mtu=1492 #$(nvram get wan_usb_mtu)
mru=1492 #$(nvram get wan_usb_mru)
vend=$(nvram get wan_modem_vid)
prod=$(nvram get wan_modem_pid)
pppdoptions=$(nvram get wan_modem_options)
initoptions=$(nvram get wan_modem_dialup_init)

usbdev=""

mkdir /tmp/ppp/peers/

echo "ABORT	'}'
ABORT	'BUSY'
ABORT 	'NO CARRIER'
ABORT	'ERROR'
ABORT 	'NO DIAL TONE'
ABORT 	'NO ANSWER'
ABORT 	'DELAYED'
REPORT	'CONNECT'
''	'ATZ'
SAY	'Calling CDMA/EVDO'
$initoptions
'OK'	'ATDT#777'
'CONNECT'	'ATO'
'' ''" > /tmp/ppp/peers/0.chat

echo "ABORT	BUSY
ABORT	'NO CARRIER'
ABORT	ERROR
REPORT	CONNECT
''	'ATZ'
$initoptions
SAY	'Calling UMTS/GPRS'
''	'AT+CGDCONT=1,\"IP\",\"$apn\"'
'OK'	'ATD$dialnumber'
'CONNECT'	''" > /tmp/ppp/peers/1.chat

write_dialup_file()
{
  [[ -z  $usbdev ]] || return;

  if [ -c /dev/usb/acm/$port ]; then
   usbdev="/dev/usb/acm/$port"
  else
   usbdev="/dev/usb/tts/$port"
  fi

echo "debug
$usbdev
$portspeed
crtscts
noipdefault
ipcp-accept-local
lcp-echo-interval 60
lcp-echo-failure 6
mtu $mtu
mru $mru
usepeerdns
noauth
$pppdoptionss
maxfail 2
nodetach
persist
linkname wan0
user '$username'
password '$password'
connect \"/usr/sbin/chat -s -S -V -t 60 -f /tmp/ppp/peers/$modem.chat 2>/tmp/chat.log\"" > /tmp/ppp/peers/dialup
}

while true; do
  sleep 5
  if [ "$vend" == "" -o "$prod" == "" ]; then
   rmmod  option
   rmmod  acm

   insmod acm
   insmod option
  else
   rmmod usbserial

   insmod usbserial vendor=$vend product=$prod maxSize=4096
  fi
  sleep 20
  write_dialup_file

  pppd call dialup >> /tmp/chat.log 2>&1
  echo "Reconnect. Device: $usbdev" >> /tmp/chat.log
done
