#!/bin/sh

#  Modem Status script for 3G modem
#  ver. 1.005 beta 27.02.2011
#  by dlukanidin, rss

getKernel() {
	kernel="$(uname -r)"
	kernel=${kernel:0:3}
	if [ "$kernel" = "2.4" ]; then
		acm_mod="acm"
	else
		acm_mod="cdc-acm"
	fi
}

isDriversLoaded() {
	[ -z "$acm_mod" ] && getKernel
	usbserial="$(lsmod | grep usbserial)"
	acm="$(lsmod | grep $acm_mod)"
	[ -z "$usbserial" ] && [ -z "$acm" ] && return 1
	return 0
}

printHelp() {
	echo
	echo "Can't recive status information."
	echo "--------------------------------"
	echo "Need user defined script in $userFile"
	echo "This script is called with next parameters:"
	echo "   PORT - modem UI port"
	echo "   COMMAND - i | s | r request | t"
	echo "Commands:"
	echo "   i  echo static modem information. Manufacturer,..."
	echo "   s  echo signal information."
	echo "   r  echo answer to request modem or ISP Info."
	echo "      If request start from symbols 'AT' then it is AT command."
	echo "      In other cases this is USSD request."
	echo "   t  echo traffic information."
	echo "All answers must be HTML compatible coded."
	echo "Examples: $huaweiFile, $zteFile, $anydataFile"
	echo
}

if ! isDriversLoaded; then
    echo "Modem drivers not loaded"
    exit 1
fi

devpath_name='/proc/bus/usb/devpath'
tmp_name='/tmp/stat.tmp'
modem_conf_name='/usr/share/modem/modems.conf'
loc=$1
port=$(grep ": $loc :" "$devpath_name" | awk -F':' '{print $1}')
lsmodem -c $modem_conf_name > $tmp_name
loc=${loc%.*}
type=$(grep ":$loc:" "$tmp_name" | cut -d: -f4)
rm $tmp_name

if [ -z $port ] || [ ! -e $port ]; then
    echo "Modem port in location $loc not exist"
    exit 2
fi

userFile="/usr/local/sbin/state_3g_modem"
huaweiFile="/usr/share/modem/bin/state_3g_huawei"
zteFile="/usr/share/modem/bin/state_3g_zte"
anydataFile="/usr/share/modem/bin/state_3g_anydata"

echo "<html><head>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">
</head><body><pre>"

if [ -e $userFile ]; then
	$userFile $port $2 $3
else
	if [ "$type" == "W" ]; then		#WCDMA modems
		if [ ! -z "$(cat /proc/bus/usb/devpath | grep $1 | grep HUAWEI)" ]; then
			$huaweiFile $port $2 $3
		elif [ ! -z "$(cat /proc/bus/usb/devpath | grep $1 | grep ZTE)" ]; then
			$zteFile $port $2 $3
		else
			printHelp
		fi
	elif [ "$type" == "C" ]; then	# CDMA modems
		if [ ! -z "$(cat /proc/bus/usb/devpath | grep $1 | grep AnyDATA)" ]; then
			$anydataFile $port $2 $3
		else
			printHelp
		fi
	else	# user defined dial script
		printHelp
	fi
fi

echo "</pre></body></html>"
