/*
 * Copyright (C) 2009, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: epivers.h,v 1.1.1.1 2010/11/22 09:05:02 Exp $
 *
*/

#ifndef _epivers_h_
#define _epivers_h_

#define	EPI_MAJOR_VERSION	5

#define	EPI_MINOR_VERSION	60

#define	EPI_RC_NUMBER		127

#define	EPI_INCREMENTAL_NUMBER	5

#define EPI_BUILD_NUMBER	2

#define	EPI_VERSION		5, 60, 127, 5

#define	EPI_VERSION_NUM		0x053c7f05

#define EPI_VERSION_DEV		5.60.0

/* Driver Version String, ASCII, 32 chars max */
#ifdef WLTEST
#define	EPI_VERSION_STR		"5.60.127.5  (WLTEST)"
#else
#define	EPI_VERSION_STR		"5.60.127.5 "
#endif

#endif /* _epivers_h_ */
