#!/bin/sh
if [ "$(nvram get wan_modem_packetsize)" == "0" ]; then
 insmod acm
else
 insmod acm maxpacketsize=$(nvram get wan_modem_packetsize)
fi

if [ "$(nvram get wan_modem_vid)" == "" -o "$(nvram get wan_modem_pid)" == "" ]; then
 insmod usbserial
else
 if [ "$(nvram get wan_modem_packetsize)" == "0" ]; then
  insmod usbserial vendor=$(nvram get wan_modem_vid) product=$(nvram get wan_modem_pid)
 else
  insmod usbserial vendor=$(nvram get wan_modem_vid) product=$(nvram get wan_modem_pid) maxpacketsize=$(nvram get wan_modem_packetsize)
 fi
fi

insmod pl2303
insmod ftdi_sio

while true; do
  kill -9 $(ps|grep pppd|grep gprs|awk -F' ' '{print $1}') 2>/dev/null
  rmmod option
  /usr/ppp/zerocd >> /tmp/chat.log 2>&1
  insmod option
  sleep 5

  if [ -z "$(nvram get wan_modem_usbloc)" ]; then
   if [ -c /dev/usb/acm/0 ]; then
    DEVICE="/dev/usb/acm/0"
   else
    DEVICE="/dev/usb/tts/0"
   fi
  else
   DEVICE=$(grep ": $(nvram get wan_modem_usbloc) :" /proc/bus/usb/devpath | awk -F':' '{print $1}')
  fi
  
  export DEVICE
  
  /usr/ppp/gprs/update $1

  pppd file /tmp/ppp/peers/gprs >> /tmp/chat.log 2>&1

  sleep 25
done
